package org.mountsinai.mortalitytriggersystem

class MortalityReviewForm {

    /*Patient Information*/
    long id
    String visitId
    String admitUnit
    String patientName
    String mrn
    Date dob
    String gender
    Date admitDateTime
    String admittingDiagnosis
    String primaryReasonTimeOfAdmission
    String dischargeDiagnosis
    Date dischargeDateTime
    String dischargeUnit
    Date expiredDateTime
    String hospService
    String lastAttending
    String dictationCode
    String serviceTeam
    String hospitalSite
    String hospitalName
    String patientUnitAtDeath
    String dischargeAttendeeName
    String dischargingDepartment
    String dischargingDivision
    String comment
    boolean wasPatientTransferredFromAnotherFacility
    String patientTransferredComment
    boolean isIcuStay
    boolean isPatientDiedLessThan24hrsOfDischarge
    boolean isDeathOccuredWithin24hrOfAdmission
    boolean wasCaseAppropriateForME
    String wasCaseAppropriateForMEComment
    boolean isAutopsyPerformed
    String summaryOfHospitalCourse

    /* Major Comorbidities POA*/
    boolean isComorbiditiesAtrialFibrillation
    boolean isCerebrovascularAccident
    boolean isChronicStageKidneyDisease
    boolean isCirrhosis
    boolean isCognitiveImpairment
    boolean isAsthma
    boolean isCoronaryArteryDisease
    boolean isDiabetes
    boolean isDementia
    boolean isComorbiditiesHeartFailure
    boolean isHyperTension
    boolean isMalignancy
    boolean isMorbidObesity
    boolean isNeurologicalDisorders
    boolean isObstructiveSleepApnea
    boolean isPeripheralVascularDisease
    boolean isValvularHeartDisease
    boolean isComorbiditiesOther
    String comorbiditiesOtherComment

    /*Complication Acquired in Hospital */
    boolean isAcuteKidneyInjury
    boolean isAcuteMyocardialInfraction
    boolean isAlterredMentalStatus
    boolean isHospitalAtrialFibrillation
    boolean isChestPain
    boolean isCOPD
    boolean isCVA
    boolean isDVTOrVTE
    boolean isHospitalFall
    boolean isFever
    boolean isGiBleed
    boolean isHospitalHeartFailure
    boolean isHospitalHospitalAcquiredInfection
    boolean isMedicalError
    String medicalErrorComment
    boolean isPressureUlcer
    boolean isHospitalSepsis
    boolean isShortnessOfBreath
    boolean isSyncope
    boolean isTypeOrLocation
    String typeOrLocationComment
    boolean isHospitalOther
    String hospitalOtherComment

    /* Major Supportive Interventions*/
    boolean isCentralLine
    boolean isCPR
    boolean isSupportiveHemodialysis
    boolean isHemodialysisCatheter
    boolean isIntubation
    boolean isMechanicalVent
    boolean isSupportiveVasopressors
    boolean isSupportiveOther
    String supportiveOtherComment

    /* Major Invasive Interventions*/
    boolean isBronchoscopy
    boolean isCardiacCatheterization
    boolean isInvasiveHemodialysis
    boolean isInvasiveOther
    String invasiveOtherComment
    boolean isInterventionalRadiologicalProc
    boolean isSergicalProcedure
    String sergicalProcedureComment

    /* Procedure Related Complications*/
    boolean isProcedureCardiac
    String cardiacComment
    boolean isNeurologicalInjury
    boolean isDeadWithin72HoursOfProcedure
    boolean isProcedurePulmonary
    String pulmonaryComment
    boolean isExcessiveOrUnexpectedBleeding
    boolean isRenalFailure
    boolean isProcedureHepatic
    boolean isUnanticipatedTransfusion
    boolean isInfection
    String infectionComment
    boolean isProcedureVasopressors
    boolean isProcedureOther
    String procedureOtherComment
    String postOpSummary

    /*End of Life Care*/
    boolean isHospice
    boolean isPalliativeCare
    boolean wasThereAnAdvanceDirective

    /*Cause of Death*/
    boolean isBleeding
    boolean isDeathCauseCardiac
    boolean isDeathCauseHepatic
    boolean isDeathCausePulmonary
    boolean isDeathCauseRenal
    boolean isDeathCauseSepsis
    boolean isDeathCauseOther
    String deathCauseOtherComment
    boolean wasPatientAdmittedToICUTimeOfAdmission
    boolean expectedPatientToDieAdmission
    boolean isNaturalCourseOfPatientIllness
    boolean isRelatedToUnderlyingConditions
    String expectedPatientToDieAdmissionComment

    /*Contributing Factors*/
    boolean isAdverseDrugEvent
    boolean isOmissionOfCare
    boolean isDelayInTreatmentOrIntervention
    boolean isPatientCompliance
    boolean isElectronicMedicalRecord
    boolean isPoorCommunication
    boolean isContributingFall
    boolean isPoorHandoff
    boolean isFailureToAftercare
    boolean isPoorOrMissingDocumentation
    boolean isFailureToEscalate
    boolean isSupervision
    boolean isHospitalAcquiredCondition
    boolean isSurgicalOrProcedureError
    boolean isContributingHospitalAcquiredInfection
    boolean isTechniqueError
    boolean doesDeathRequireFurtherReview

    ReviewStatus status
    Date dateCreated
    String createdBy
    Date dateUpdated
    String updatedBy

    static constraints = {
        id (nullable:true)
        visitId (nullable:true)
        admitUnit (nullable:true)
        patientName (nullable:true)
        mrn (nullable:true)
        dob (nullable:true)
        gender (nullable:true)
        admitDateTime (nullable:true)
        admittingDiagnosis (nullable:true)
        primaryReasonTimeOfAdmission (nullable:true)
        dischargeDiagnosis (nullable:true)
        dischargeDateTime (nullable:true)
        dischargeUnit (nullable:true)
        expiredDateTime (nullable:true)
        hospService (nullable:true)
        lastAttending (nullable:true)
        dictationCode (nullable:true)
        serviceTeam (nullable:true)
        hospitalSite (nullable:true)
        hospitalName (nullable:true)
        patientUnitAtDeath (nullable:true)
        dischargeAttendeeName (nullable:true)
        dischargingDepartment (nullable:true)
        dischargingDivision (nullable:true)
        comment (nullable:true)
        wasPatientTransferredFromAnotherFacility (nullable:true)
        patientTransferredComment (nullable:true)
        isIcuStay (nullable:true)
        isPatientDiedLessThan24hrsOfDischarge (nullable:true)
        isDeathOccuredWithin24hrOfAdmission (nullable:true)
        wasCaseAppropriateForME (nullable:true)
        wasCaseAppropriateForMEComment (nullable:true)
        isAutopsyPerformed (nullable:true)
        summaryOfHospitalCourse (nullable:true)
        isComorbiditiesAtrialFibrillation (nullable:true)
        isCerebrovascularAccident (nullable:true)
        isChronicStageKidneyDisease (nullable:true)
        isCirrhosis (nullable:true)
        isCognitiveImpairment (nullable:true)
        isAsthma (nullable:true)
        isCoronaryArteryDisease (nullable:true)
        isDiabetes (nullable:true)
        isDementia (nullable:true)
        isComorbiditiesHeartFailure (nullable:true)
        isHyperTension (nullable:true)
        isMalignancy (nullable:true)
        isMorbidObesity (nullable:true)
        isNeurologicalDisorders (nullable:true)
        isObstructiveSleepApnea (nullable:true)
        isPeripheralVascularDisease (nullable:true)
        isValvularHeartDisease (nullable:true)
        isComorbiditiesOther (nullable:true)
        comorbiditiesOtherComment (nullable:true)
        isAcuteKidneyInjury (nullable:true)
        isAcuteMyocardialInfraction (nullable:true)
        isAlterredMentalStatus (nullable:true)
        isHospitalAtrialFibrillation (nullable:true)
        isChestPain (nullable:true)
        isCOPD (nullable:true)
        isCVA (nullable:true)
        isDVTOrVTE (nullable:true)
        isHospitalFall (nullable:true)
        isFever (nullable:true)
        isGiBleed (nullable:true)
        isHospitalHeartFailure (nullable:true)
        isHospitalHospitalAcquiredInfection (nullable:true)
        isMedicalError (nullable:true)
        medicalErrorComment (nullable:true)
        isPressureUlcer (nullable:true)
        isHospitalSepsis (nullable:true)
        isShortnessOfBreath (nullable:true)
        isSyncope (nullable:true)
        isTypeOrLocation (nullable:true)
        typeOrLocationComment (nullable:true)
        isHospitalOther (nullable:true)
        hospitalOtherComment (nullable:true)
        isCentralLine (nullable:true)
        isCPR (nullable:true)
        isSupportiveHemodialysis (nullable:true)
        isHemodialysisCatheter (nullable:true)
        isIntubation (nullable:true)
        isMechanicalVent (nullable:true)
        isSupportiveVasopressors (nullable:true)
        isSupportiveOther (nullable:true)
        supportiveOtherComment (nullable:true)
        isBronchoscopy (nullable:true)
        isCardiacCatheterization (nullable:true)
        isInvasiveHemodialysis (nullable:true)
        isInvasiveOther (nullable:true)
        invasiveOtherComment (nullable:true)
        isInterventionalRadiologicalProc (nullable:true)
        isSergicalProcedure (nullable:true)
        sergicalProcedureComment (nullable:true)
        isProcedureCardiac (nullable:true)
        cardiacComment (nullable:true)
        isNeurologicalInjury (nullable:true)
        isDeadWithin72HoursOfProcedure (nullable:true)
        isProcedurePulmonary (nullable:true)
        pulmonaryComment (nullable:true)
        isExcessiveOrUnexpectedBleeding (nullable:true)
        isRenalFailure (nullable:true)
        isProcedureHepatic (nullable:true)
        isUnanticipatedTransfusion (nullable:true)
        isInfection (nullable:true)
        infectionComment (nullable:true)
        isProcedureVasopressors (nullable:true)
        isProcedureOther (nullable:true)
        procedureOtherComment (nullable:true)
        postOpSummary (nullable:true)
        isHospice (nullable:true)
        isPalliativeCare (nullable:true)
        wasThereAnAdvanceDirective (nullable:true)
        isBleeding (nullable:true)
        isDeathCauseCardiac (nullable:true)
        isDeathCauseHepatic (nullable:true)
        isDeathCausePulmonary (nullable:true)
        isDeathCauseRenal (nullable:true)
        isDeathCauseSepsis (nullable:true)
        isDeathCauseOther (nullable:true)
        deathCauseOtherComment (nullable:true)
        wasPatientAdmittedToICUTimeOfAdmission (nullable:true)
        expectedPatientToDieAdmission (nullable:true)
        isNaturalCourseOfPatientIllness (nullable:true)
        isRelatedToUnderlyingConditions (nullable:true)
        expectedPatientToDieAdmissionComment (nullable:true)
        isAdverseDrugEvent (nullable:true)
        isOmissionOfCare (nullable:true)
        isDelayInTreatmentOrIntervention (nullable:true)
        isPatientCompliance (nullable:true)
        isElectronicMedicalRecord (nullable:true)
        isPoorCommunication (nullable:true)
        isContributingFall (nullable:true)
        isPoorHandoff (nullable:true)
        isFailureToAftercare (nullable:true)
        isPoorOrMissingDocumentation (nullable:true)
        isFailureToEscalate (nullable:true)
        isSupervision (nullable:true)
        isHospitalAcquiredCondition (nullable:true)
        isSurgicalOrProcedureError (nullable:true)
        isContributingHospitalAcquiredInfection (nullable:true)
        isTechniqueError (nullable:true)
        doesDeathRequireFurtherReview (nullable:true)
        status (nullable:true)
        dateCreated (nullable:true)
        createdBy (nullable:true)
        dateUpdated (nullable:true)
        updatedBy (nullable:true)
    }

    static mapping = {
        version false
    }
}
